export const TRANSLATEFILE = 'app/translateFile/TRANSLATEFILE';
export const TRANSLATEFILE_SUCCESS = 'app/translateFile/TRANSLATEFILE_SUCCESS';
export const TRANSLATEFILE_FAIL = 'app/translateFile/TRANSLATEFILE_FAIL';
export const CHANGE_FILE = 'app/translateFile/CHANGE_FILE';
export const CHANGE_FILE_DOCUMENT = 'app/translateFile/CHANGE_FILE_DOCUMENT';
export const CHANGE_OUTPUT = 'app/translateFile/CHANGE_OUTPUT';
export const CHANGE_OUTPUT_DOCUMENT = 'app/translateFile/CHANGE_OUTPUT_DOCUMENT';
export const TRANSLATEFILE_DOCUMENT_SUCCESS = 'app/translateFile/TRANSLATEFILE_DOCUMENT_SUCCESS';
export const DETECTLANG_FILE = 'app/translateFile/DETECTLANG_FILE';
export const DETECTLANG_FILE_FAIL = 'app/translateFile/DETECTLANG_FILE_FAIL';
export const DETECTLANG_FILE_SUCCESS = 'app/translateFile/DETECTLANG_FILE_SUCCESS';
export const TRANSLATE_AFTER_DETECTLANG_FILE_SUCCESS = 'app/translateFile/TRANSLATE_AFTER_DETECTLANG_FILE_SUCCESS';

export const GETTING_SINGLE_LANG_DETECTION_HISTORY_SUCCESS = 'app/translateFile/GETTING_SINGLE_LANG_DETECTION_HISTORY_SUCCESS';
export const GETTING_SINGLE_TRANSLATION_HISTORY_SUCCESS = 'app/translateFile/GETTING_SINGLE_TRANSLATION_HISTORY_SUCCESS';
